from __future__ import annotations

from datetime import datetime
from typing import Protocol

from .entidades import DadosIdentidade, PaginaAntecedentes, RecenseamentoMilitar


class RepositorioRecenseamentoMilitar(Protocol):
    def adicionar(self, item: RecenseamentoMilitar) -> RecenseamentoMilitar: ...
    def obter(self, item_id: int) -> RecenseamentoMilitar | None: ...
    def obter_por_bi(self, numero_bi: str) -> RecenseamentoMilitar | None: ...
    def obter_por_numero(self, numero_recenseamento: str) -> RecenseamentoMilitar | None: ...
    def listar(self, pagina: int, tamanho_pagina: int, numero_bi: str | None = None) -> tuple[list[RecenseamentoMilitar], int]: ...
    def actualizar(self, item: RecenseamentoMilitar) -> RecenseamentoMilitar: ...
    def ultima_actualizacao(self) -> datetime | None: ...


class ValidadorIdentidade(Protocol):
    def procurar(self, numero_bi: str) -> DadosIdentidade | None: ...


class ConsultorAntecedentes(Protocol):
    def consultar(self, numero_bi: str, pagina: int, tamanho_pagina: int) -> PaginaAntecedentes: ...
