from __future__ import annotations
from datetime import datetime
from typing import Protocol
from .entidades import RegistoCriminal, DadosIdentidade


class RepositorioRegistoCriminal(Protocol):
    def adicionar_registo(self, record: RegistoCriminal) -> RegistoCriminal: ...
    def obter_registo(self, record_id: int) -> RegistoCriminal | None: ...
    def obter_registo_por_processo(self, numero_processo: str) -> RegistoCriminal | None: ...
    def listar_registos(self, page: int, page_size: int, numero_bi: str | None = None) -> tuple[list[RegistoCriminal], int]: ...
    def actualizar_registo(self, record: RegistoCriminal) -> RegistoCriminal: ...
    def ultima_actualizacao_registo(self) -> datetime | None: ...
class ValidadorIdentidade(Protocol):
    def procurar(self, numero_bi: str) -> DadosIdentidade | None: ...
