# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from servico_militar.v1 import servico_militar_pb2 as servico__militar_dot_v1_dot_servico__militar__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in servico_militar/v1/servico_militar_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServicoMilitarStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VerificarSaude = channel.unary_unary(
                '/sisp.servico_militar.v1.ServicoMilitar/VerificarSaude',
                request_serializer=servico__militar_dot_v1_dot_servico__militar__pb2.PedidoSaude.SerializeToString,
                response_deserializer=servico__militar_dot_v1_dot_servico__militar__pb2.RespostaSaude.FromString,
                _registered_method=True)
        self.CriarRecenseamento = channel.unary_unary(
                '/sisp.servico_militar.v1.ServicoMilitar/CriarRecenseamento',
                request_serializer=servico__militar_dot_v1_dot_servico__militar__pb2.PedidoCriarRecenseamento.SerializeToString,
                response_deserializer=servico__militar_dot_v1_dot_servico__militar__pb2.RecenseamentoMilitar.FromString,
                _registered_method=True)
        self.ObterRecenseamento = channel.unary_unary(
                '/sisp.servico_militar.v1.ServicoMilitar/ObterRecenseamento',
                request_serializer=servico__militar_dot_v1_dot_servico__militar__pb2.PedidoObterRecenseamento.SerializeToString,
                response_deserializer=servico__militar_dot_v1_dot_servico__militar__pb2.RecenseamentoMilitar.FromString,
                _registered_method=True)
        self.ConsultarSituacao = channel.unary_unary(
                '/sisp.servico_militar.v1.ServicoMilitar/ConsultarSituacao',
                request_serializer=servico__militar_dot_v1_dot_servico__militar__pb2.PedidoConsultarSituacao.SerializeToString,
                response_deserializer=servico__militar_dot_v1_dot_servico__militar__pb2.RecenseamentoMilitar.FromString,
                _registered_method=True)
        self.ListarRecenseamentos = channel.unary_unary(
                '/sisp.servico_militar.v1.ServicoMilitar/ListarRecenseamentos',
                request_serializer=servico__militar_dot_v1_dot_servico__militar__pb2.PedidoListarRecenseamentos.SerializeToString,
                response_deserializer=servico__militar_dot_v1_dot_servico__militar__pb2.RespostaListarRecenseamentos.FromString,
                _registered_method=True)
        self.ActualizarRecenseamento = channel.unary_unary(
                '/sisp.servico_militar.v1.ServicoMilitar/ActualizarRecenseamento',
                request_serializer=servico__militar_dot_v1_dot_servico__militar__pb2.PedidoActualizarRecenseamento.SerializeToString,
                response_deserializer=servico__militar_dot_v1_dot_servico__militar__pb2.RecenseamentoMilitar.FromString,
                _registered_method=True)
        self.ValidarIdentidade = channel.unary_unary(
                '/sisp.servico_militar.v1.ServicoMilitar/ValidarIdentidade',
                request_serializer=servico__militar_dot_v1_dot_servico__militar__pb2.PedidoValidarIdentidade.SerializeToString,
                response_deserializer=servico__militar_dot_v1_dot_servico__militar__pb2.ValidacaoIdentidade.FromString,
                _registered_method=True)
        self.ConsultarAntecedentes = channel.unary_unary(
                '/sisp.servico_militar.v1.ServicoMilitar/ConsultarAntecedentes',
                request_serializer=servico__militar_dot_v1_dot_servico__militar__pb2.PedidoConsultarAntecedentes.SerializeToString,
                response_deserializer=servico__militar_dot_v1_dot_servico__militar__pb2.RespostaAntecedentes.FromString,
                _registered_method=True)


class ServicoMilitarServicer(object):
    """Missing associated documentation comment in .proto file."""

    def VerificarSaude(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CriarRecenseamento(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObterRecenseamento(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarSituacao(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarRecenseamentos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActualizarRecenseamento(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidarIdentidade(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarAntecedentes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServicoMilitarServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VerificarSaude': grpc.unary_unary_rpc_method_handler(
                    servicer.VerificarSaude,
                    request_deserializer=servico__militar_dot_v1_dot_servico__militar__pb2.PedidoSaude.FromString,
                    response_serializer=servico__militar_dot_v1_dot_servico__militar__pb2.RespostaSaude.SerializeToString,
            ),
            'CriarRecenseamento': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarRecenseamento,
                    request_deserializer=servico__militar_dot_v1_dot_servico__militar__pb2.PedidoCriarRecenseamento.FromString,
                    response_serializer=servico__militar_dot_v1_dot_servico__militar__pb2.RecenseamentoMilitar.SerializeToString,
            ),
            'ObterRecenseamento': grpc.unary_unary_rpc_method_handler(
                    servicer.ObterRecenseamento,
                    request_deserializer=servico__militar_dot_v1_dot_servico__militar__pb2.PedidoObterRecenseamento.FromString,
                    response_serializer=servico__militar_dot_v1_dot_servico__militar__pb2.RecenseamentoMilitar.SerializeToString,
            ),
            'ConsultarSituacao': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarSituacao,
                    request_deserializer=servico__militar_dot_v1_dot_servico__militar__pb2.PedidoConsultarSituacao.FromString,
                    response_serializer=servico__militar_dot_v1_dot_servico__militar__pb2.RecenseamentoMilitar.SerializeToString,
            ),
            'ListarRecenseamentos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarRecenseamentos,
                    request_deserializer=servico__militar_dot_v1_dot_servico__militar__pb2.PedidoListarRecenseamentos.FromString,
                    response_serializer=servico__militar_dot_v1_dot_servico__militar__pb2.RespostaListarRecenseamentos.SerializeToString,
            ),
            'ActualizarRecenseamento': grpc.unary_unary_rpc_method_handler(
                    servicer.ActualizarRecenseamento,
                    request_deserializer=servico__militar_dot_v1_dot_servico__militar__pb2.PedidoActualizarRecenseamento.FromString,
                    response_serializer=servico__militar_dot_v1_dot_servico__militar__pb2.RecenseamentoMilitar.SerializeToString,
            ),
            'ValidarIdentidade': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidarIdentidade,
                    request_deserializer=servico__militar_dot_v1_dot_servico__militar__pb2.PedidoValidarIdentidade.FromString,
                    response_serializer=servico__militar_dot_v1_dot_servico__militar__pb2.ValidacaoIdentidade.SerializeToString,
            ),
            'ConsultarAntecedentes': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarAntecedentes,
                    request_deserializer=servico__militar_dot_v1_dot_servico__militar__pb2.PedidoConsultarAntecedentes.FromString,
                    response_serializer=servico__militar_dot_v1_dot_servico__militar__pb2.RespostaAntecedentes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sisp.servico_militar.v1.ServicoMilitar', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sisp.servico_militar.v1.ServicoMilitar', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServicoMilitar(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def VerificarSaude(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sisp.servico_militar.v1.ServicoMilitar/VerificarSaude',
            servico__militar_dot_v1_dot_servico__militar__pb2.PedidoSaude.SerializeToString,
            servico__militar_dot_v1_dot_servico__militar__pb2.RespostaSaude.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CriarRecenseamento(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sisp.servico_militar.v1.ServicoMilitar/CriarRecenseamento',
            servico__militar_dot_v1_dot_servico__militar__pb2.PedidoCriarRecenseamento.SerializeToString,
            servico__militar_dot_v1_dot_servico__militar__pb2.RecenseamentoMilitar.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObterRecenseamento(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sisp.servico_militar.v1.ServicoMilitar/ObterRecenseamento',
            servico__militar_dot_v1_dot_servico__militar__pb2.PedidoObterRecenseamento.SerializeToString,
            servico__militar_dot_v1_dot_servico__militar__pb2.RecenseamentoMilitar.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarSituacao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sisp.servico_militar.v1.ServicoMilitar/ConsultarSituacao',
            servico__militar_dot_v1_dot_servico__militar__pb2.PedidoConsultarSituacao.SerializeToString,
            servico__militar_dot_v1_dot_servico__militar__pb2.RecenseamentoMilitar.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarRecenseamentos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sisp.servico_militar.v1.ServicoMilitar/ListarRecenseamentos',
            servico__militar_dot_v1_dot_servico__militar__pb2.PedidoListarRecenseamentos.SerializeToString,
            servico__militar_dot_v1_dot_servico__militar__pb2.RespostaListarRecenseamentos.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActualizarRecenseamento(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sisp.servico_militar.v1.ServicoMilitar/ActualizarRecenseamento',
            servico__militar_dot_v1_dot_servico__militar__pb2.PedidoActualizarRecenseamento.SerializeToString,
            servico__militar_dot_v1_dot_servico__militar__pb2.RecenseamentoMilitar.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidarIdentidade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sisp.servico_militar.v1.ServicoMilitar/ValidarIdentidade',
            servico__militar_dot_v1_dot_servico__militar__pb2.PedidoValidarIdentidade.SerializeToString,
            servico__militar_dot_v1_dot_servico__militar__pb2.ValidacaoIdentidade.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarAntecedentes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sisp.servico_militar.v1.ServicoMilitar/ConsultarAntecedentes',
            servico__militar_dot_v1_dot_servico__militar__pb2.PedidoConsultarAntecedentes.SerializeToString,
            servico__militar_dot_v1_dot_servico__militar__pb2.RespostaAntecedentes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
