# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: comum/v1/comum.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'comum/v1/comum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63omum/v1/comum.proto\x12\rsisp.comum.v1\"Q\n\x0e\x43ontextoPedido\x12\x11\n\tid_pedido\x18\x01 \x01(\t\x12\x18\n\x10servico_chamador\x18\x02 \x01(\t\x12\x12\n\nfinalidade\x18\x03 \x01(\t\"6\n\x11ResultadoOperacao\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comum.v1.comum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTEXTOPEDIDO']._serialized_start=39
  _globals['_CONTEXTOPEDIDO']._serialized_end=120
  _globals['_RESULTADOOPERACAO']._serialized_start=122
  _globals['_RESULTADOOPERACAO']._serialized_end=176
# @@protoc_insertion_point(module_scope)
