# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from identificacao_civil.v1 import identificacao_civil_pb2 as identificacao__civil_dot_v1_dot_identificacao__civil__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in identificacao_civil/v1/identificacao_civil_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServicoIdentificacaoCivilStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VerificarSaude = channel.unary_unary(
                '/sisp.identificacao_civil.v1.ServicoIdentificacaoCivil/VerificarSaude',
                request_serializer=identificacao__civil_dot_v1_dot_identificacao__civil__pb2.PedidoSaude.SerializeToString,
                response_deserializer=identificacao__civil_dot_v1_dot_identificacao__civil__pb2.RespostaSaude.FromString,
                _registered_method=True)
        self.RegistarCidadao = channel.unary_unary(
                '/sisp.identificacao_civil.v1.ServicoIdentificacaoCivil/RegistarCidadao',
                request_serializer=identificacao__civil_dot_v1_dot_identificacao__civil__pb2.PedidoRegistarCidadao.SerializeToString,
                response_deserializer=identificacao__civil_dot_v1_dot_identificacao__civil__pb2.Cidadao.FromString,
                _registered_method=True)
        self.ObterCidadao = channel.unary_unary(
                '/sisp.identificacao_civil.v1.ServicoIdentificacaoCivil/ObterCidadao',
                request_serializer=identificacao__civil_dot_v1_dot_identificacao__civil__pb2.PedidoObterCidadao.SerializeToString,
                response_deserializer=identificacao__civil_dot_v1_dot_identificacao__civil__pb2.Cidadao.FromString,
                _registered_method=True)
        self.ProcurarCidadaoPorBi = channel.unary_unary(
                '/sisp.identificacao_civil.v1.ServicoIdentificacaoCivil/ProcurarCidadaoPorBi',
                request_serializer=identificacao__civil_dot_v1_dot_identificacao__civil__pb2.PedidoProcurarCidadaoPorBi.SerializeToString,
                response_deserializer=identificacao__civil_dot_v1_dot_identificacao__civil__pb2.Cidadao.FromString,
                _registered_method=True)
        self.ListarCidadaos = channel.unary_unary(
                '/sisp.identificacao_civil.v1.ServicoIdentificacaoCivil/ListarCidadaos',
                request_serializer=identificacao__civil_dot_v1_dot_identificacao__civil__pb2.PedidoListarCidadaos.SerializeToString,
                response_deserializer=identificacao__civil_dot_v1_dot_identificacao__civil__pb2.RespostaListarCidadaos.FromString,
                _registered_method=True)
        self.ActualizarCidadao = channel.unary_unary(
                '/sisp.identificacao_civil.v1.ServicoIdentificacaoCivil/ActualizarCidadao',
                request_serializer=identificacao__civil_dot_v1_dot_identificacao__civil__pb2.PedidoActualizarCidadao.SerializeToString,
                response_deserializer=identificacao__civil_dot_v1_dot_identificacao__civil__pb2.Cidadao.FromString,
                _registered_method=True)
        self.ObterHistoricoCriminal = channel.unary_unary(
                '/sisp.identificacao_civil.v1.ServicoIdentificacaoCivil/ObterHistoricoCriminal',
                request_serializer=identificacao__civil_dot_v1_dot_identificacao__civil__pb2.PedidoHistoricoCriminal.SerializeToString,
                response_deserializer=identificacao__civil_dot_v1_dot_identificacao__civil__pb2.RespostaHistoricoCriminal.FromString,
                _registered_method=True)


class ServicoIdentificacaoCivilServicer(object):
    """Missing associated documentation comment in .proto file."""

    def VerificarSaude(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegistarCidadao(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObterCidadao(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcurarCidadaoPorBi(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarCidadaos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActualizarCidadao(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObterHistoricoCriminal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServicoIdentificacaoCivilServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VerificarSaude': grpc.unary_unary_rpc_method_handler(
                    servicer.VerificarSaude,
                    request_deserializer=identificacao__civil_dot_v1_dot_identificacao__civil__pb2.PedidoSaude.FromString,
                    response_serializer=identificacao__civil_dot_v1_dot_identificacao__civil__pb2.RespostaSaude.SerializeToString,
            ),
            'RegistarCidadao': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistarCidadao,
                    request_deserializer=identificacao__civil_dot_v1_dot_identificacao__civil__pb2.PedidoRegistarCidadao.FromString,
                    response_serializer=identificacao__civil_dot_v1_dot_identificacao__civil__pb2.Cidadao.SerializeToString,
            ),
            'ObterCidadao': grpc.unary_unary_rpc_method_handler(
                    servicer.ObterCidadao,
                    request_deserializer=identificacao__civil_dot_v1_dot_identificacao__civil__pb2.PedidoObterCidadao.FromString,
                    response_serializer=identificacao__civil_dot_v1_dot_identificacao__civil__pb2.Cidadao.SerializeToString,
            ),
            'ProcurarCidadaoPorBi': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcurarCidadaoPorBi,
                    request_deserializer=identificacao__civil_dot_v1_dot_identificacao__civil__pb2.PedidoProcurarCidadaoPorBi.FromString,
                    response_serializer=identificacao__civil_dot_v1_dot_identificacao__civil__pb2.Cidadao.SerializeToString,
            ),
            'ListarCidadaos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarCidadaos,
                    request_deserializer=identificacao__civil_dot_v1_dot_identificacao__civil__pb2.PedidoListarCidadaos.FromString,
                    response_serializer=identificacao__civil_dot_v1_dot_identificacao__civil__pb2.RespostaListarCidadaos.SerializeToString,
            ),
            'ActualizarCidadao': grpc.unary_unary_rpc_method_handler(
                    servicer.ActualizarCidadao,
                    request_deserializer=identificacao__civil_dot_v1_dot_identificacao__civil__pb2.PedidoActualizarCidadao.FromString,
                    response_serializer=identificacao__civil_dot_v1_dot_identificacao__civil__pb2.Cidadao.SerializeToString,
            ),
            'ObterHistoricoCriminal': grpc.unary_unary_rpc_method_handler(
                    servicer.ObterHistoricoCriminal,
                    request_deserializer=identificacao__civil_dot_v1_dot_identificacao__civil__pb2.PedidoHistoricoCriminal.FromString,
                    response_serializer=identificacao__civil_dot_v1_dot_identificacao__civil__pb2.RespostaHistoricoCriminal.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sisp.identificacao_civil.v1.ServicoIdentificacaoCivil', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sisp.identificacao_civil.v1.ServicoIdentificacaoCivil', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServicoIdentificacaoCivil(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def VerificarSaude(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sisp.identificacao_civil.v1.ServicoIdentificacaoCivil/VerificarSaude',
            identificacao__civil_dot_v1_dot_identificacao__civil__pb2.PedidoSaude.SerializeToString,
            identificacao__civil_dot_v1_dot_identificacao__civil__pb2.RespostaSaude.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegistarCidadao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sisp.identificacao_civil.v1.ServicoIdentificacaoCivil/RegistarCidadao',
            identificacao__civil_dot_v1_dot_identificacao__civil__pb2.PedidoRegistarCidadao.SerializeToString,
            identificacao__civil_dot_v1_dot_identificacao__civil__pb2.Cidadao.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObterCidadao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sisp.identificacao_civil.v1.ServicoIdentificacaoCivil/ObterCidadao',
            identificacao__civil_dot_v1_dot_identificacao__civil__pb2.PedidoObterCidadao.SerializeToString,
            identificacao__civil_dot_v1_dot_identificacao__civil__pb2.Cidadao.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcurarCidadaoPorBi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sisp.identificacao_civil.v1.ServicoIdentificacaoCivil/ProcurarCidadaoPorBi',
            identificacao__civil_dot_v1_dot_identificacao__civil__pb2.PedidoProcurarCidadaoPorBi.SerializeToString,
            identificacao__civil_dot_v1_dot_identificacao__civil__pb2.Cidadao.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarCidadaos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sisp.identificacao_civil.v1.ServicoIdentificacaoCivil/ListarCidadaos',
            identificacao__civil_dot_v1_dot_identificacao__civil__pb2.PedidoListarCidadaos.SerializeToString,
            identificacao__civil_dot_v1_dot_identificacao__civil__pb2.RespostaListarCidadaos.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActualizarCidadao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sisp.identificacao_civil.v1.ServicoIdentificacaoCivil/ActualizarCidadao',
            identificacao__civil_dot_v1_dot_identificacao__civil__pb2.PedidoActualizarCidadao.SerializeToString,
            identificacao__civil_dot_v1_dot_identificacao__civil__pb2.Cidadao.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObterHistoricoCriminal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sisp.identificacao_civil.v1.ServicoIdentificacaoCivil/ObterHistoricoCriminal',
            identificacao__civil_dot_v1_dot_identificacao__civil__pb2.PedidoHistoricoCriminal.SerializeToString,
            identificacao__civil_dot_v1_dot_identificacao__civil__pb2.RespostaHistoricoCriminal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
