# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from registo_criminal.v1 import registo_criminal_pb2 as registo__criminal_dot_v1_dot_registo__criminal__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in registo_criminal/v1/registo_criminal_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServicoRegistoCriminalStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VerificarSaude = channel.unary_unary(
                '/sisp.registo_criminal.v1.ServicoRegistoCriminal/VerificarSaude',
                request_serializer=registo__criminal_dot_v1_dot_registo__criminal__pb2.PedidoSaude.SerializeToString,
                response_deserializer=registo__criminal_dot_v1_dot_registo__criminal__pb2.RespostaSaude.FromString,
                _registered_method=True)
        self.CriarRegisto = channel.unary_unary(
                '/sisp.registo_criminal.v1.ServicoRegistoCriminal/CriarRegisto',
                request_serializer=registo__criminal_dot_v1_dot_registo__criminal__pb2.PedidoCriarRegisto.SerializeToString,
                response_deserializer=registo__criminal_dot_v1_dot_registo__criminal__pb2.RegistoCriminal.FromString,
                _registered_method=True)
        self.ObterRegisto = channel.unary_unary(
                '/sisp.registo_criminal.v1.ServicoRegistoCriminal/ObterRegisto',
                request_serializer=registo__criminal_dot_v1_dot_registo__criminal__pb2.PedidoObterRegisto.SerializeToString,
                response_deserializer=registo__criminal_dot_v1_dot_registo__criminal__pb2.RegistoCriminal.FromString,
                _registered_method=True)
        self.ListarRegistos = channel.unary_unary(
                '/sisp.registo_criminal.v1.ServicoRegistoCriminal/ListarRegistos',
                request_serializer=registo__criminal_dot_v1_dot_registo__criminal__pb2.PedidoListarRegistos.SerializeToString,
                response_deserializer=registo__criminal_dot_v1_dot_registo__criminal__pb2.RespostaListarRegistos.FromString,
                _registered_method=True)
        self.ActualizarRegisto = channel.unary_unary(
                '/sisp.registo_criminal.v1.ServicoRegistoCriminal/ActualizarRegisto',
                request_serializer=registo__criminal_dot_v1_dot_registo__criminal__pb2.PedidoActualizarRegisto.SerializeToString,
                response_deserializer=registo__criminal_dot_v1_dot_registo__criminal__pb2.RegistoCriminal.FromString,
                _registered_method=True)
        self.ValidarIdentidade = channel.unary_unary(
                '/sisp.registo_criminal.v1.ServicoRegistoCriminal/ValidarIdentidade',
                request_serializer=registo__criminal_dot_v1_dot_registo__criminal__pb2.PedidoValidarIdentidade.SerializeToString,
                response_deserializer=registo__criminal_dot_v1_dot_registo__criminal__pb2.ValidacaoIdentidade.FromString,
                _registered_method=True)


class ServicoRegistoCriminalServicer(object):
    """Missing associated documentation comment in .proto file."""

    def VerificarSaude(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CriarRegisto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObterRegisto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarRegistos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActualizarRegisto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidarIdentidade(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServicoRegistoCriminalServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VerificarSaude': grpc.unary_unary_rpc_method_handler(
                    servicer.VerificarSaude,
                    request_deserializer=registo__criminal_dot_v1_dot_registo__criminal__pb2.PedidoSaude.FromString,
                    response_serializer=registo__criminal_dot_v1_dot_registo__criminal__pb2.RespostaSaude.SerializeToString,
            ),
            'CriarRegisto': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarRegisto,
                    request_deserializer=registo__criminal_dot_v1_dot_registo__criminal__pb2.PedidoCriarRegisto.FromString,
                    response_serializer=registo__criminal_dot_v1_dot_registo__criminal__pb2.RegistoCriminal.SerializeToString,
            ),
            'ObterRegisto': grpc.unary_unary_rpc_method_handler(
                    servicer.ObterRegisto,
                    request_deserializer=registo__criminal_dot_v1_dot_registo__criminal__pb2.PedidoObterRegisto.FromString,
                    response_serializer=registo__criminal_dot_v1_dot_registo__criminal__pb2.RegistoCriminal.SerializeToString,
            ),
            'ListarRegistos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarRegistos,
                    request_deserializer=registo__criminal_dot_v1_dot_registo__criminal__pb2.PedidoListarRegistos.FromString,
                    response_serializer=registo__criminal_dot_v1_dot_registo__criminal__pb2.RespostaListarRegistos.SerializeToString,
            ),
            'ActualizarRegisto': grpc.unary_unary_rpc_method_handler(
                    servicer.ActualizarRegisto,
                    request_deserializer=registo__criminal_dot_v1_dot_registo__criminal__pb2.PedidoActualizarRegisto.FromString,
                    response_serializer=registo__criminal_dot_v1_dot_registo__criminal__pb2.RegistoCriminal.SerializeToString,
            ),
            'ValidarIdentidade': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidarIdentidade,
                    request_deserializer=registo__criminal_dot_v1_dot_registo__criminal__pb2.PedidoValidarIdentidade.FromString,
                    response_serializer=registo__criminal_dot_v1_dot_registo__criminal__pb2.ValidacaoIdentidade.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sisp.registo_criminal.v1.ServicoRegistoCriminal', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sisp.registo_criminal.v1.ServicoRegistoCriminal', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServicoRegistoCriminal(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def VerificarSaude(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sisp.registo_criminal.v1.ServicoRegistoCriminal/VerificarSaude',
            registo__criminal_dot_v1_dot_registo__criminal__pb2.PedidoSaude.SerializeToString,
            registo__criminal_dot_v1_dot_registo__criminal__pb2.RespostaSaude.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CriarRegisto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sisp.registo_criminal.v1.ServicoRegistoCriminal/CriarRegisto',
            registo__criminal_dot_v1_dot_registo__criminal__pb2.PedidoCriarRegisto.SerializeToString,
            registo__criminal_dot_v1_dot_registo__criminal__pb2.RegistoCriminal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObterRegisto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sisp.registo_criminal.v1.ServicoRegistoCriminal/ObterRegisto',
            registo__criminal_dot_v1_dot_registo__criminal__pb2.PedidoObterRegisto.SerializeToString,
            registo__criminal_dot_v1_dot_registo__criminal__pb2.RegistoCriminal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarRegistos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sisp.registo_criminal.v1.ServicoRegistoCriminal/ListarRegistos',
            registo__criminal_dot_v1_dot_registo__criminal__pb2.PedidoListarRegistos.SerializeToString,
            registo__criminal_dot_v1_dot_registo__criminal__pb2.RespostaListarRegistos.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActualizarRegisto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sisp.registo_criminal.v1.ServicoRegistoCriminal/ActualizarRegisto',
            registo__criminal_dot_v1_dot_registo__criminal__pb2.PedidoActualizarRegisto.SerializeToString,
            registo__criminal_dot_v1_dot_registo__criminal__pb2.RegistoCriminal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidarIdentidade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sisp.registo_criminal.v1.ServicoRegistoCriminal/ValidarIdentidade',
            registo__criminal_dot_v1_dot_registo__criminal__pb2.PedidoValidarIdentidade.SerializeToString,
            registo__criminal_dot_v1_dot_registo__criminal__pb2.ValidacaoIdentidade.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
